defaults:
 -
  scope:
    path: ""
    type: "pages"
    values:
      layout: "default"
  scope:
    name: "readme.md"
    type: "pages"
    values:
      permalink: "index.htm"
      layout: "default"
  scope:
    name: "description.md"
    type: "pages"
    values:
      title: "Description"

remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
