defaults:
 -
  scope:
    path: ""
    type: "pages"
    values:
      layout: "default"
  scope:
    name: "readme.md"
    type: "pages"
    values:
      permalink: "index.htm"
      layout: "default"
