defaults:
 -
  scope:
    path: ""
    type: "pages"
    values:
      layout: "default"
  scope:
    name: "readme.md"
    type: "pages"
    values:
      permalink: "index.htm"
      layout: "default"
  scope:
    name: "description.md"
    type: "pages"
     values:
      title: "Description"

theme: jekyll-theme-midnight
